export const texts = [
  {lyric:"Clear blue water High tide came and brought you in",id:'ZAA'},
  {lyric:"And I could go on and on, on and on, and I will Skies grew darker",id:"ZBB"},
  {lyric:"Currents swept you out again And you were just gone and gone, gone and gone",id:"ZCC"},
  {lyric:"In silent screams In wildest dreams I never dreamed of this",id:"ZDD"},
  {lyric:"This love is good, this love is bad",id:"ZEE"},
  {lyric:"This love is alive, back from the dead (oh, oh, oh)",id:"ZZZ"},
  {lyric:"These hands had to let it go free And this love came back to me (oh, oh, oh)",id:"ZFF"},
  {lyric:"Oh, oh, oh Oh, oh, oh",id:"ZGG"},
  {lyric:"Tossing, turning Struggled through the night with someone new",id:"ZHH"},
  {lyric:"Baby, I could go on and on, on and on Lantern burning",id:"ZII"},
  {lyric:"Flickered in my mind for only you But you were still gone, gone, gone",id:"ZJJ"},
  {lyric:"In losing grip On sinking ships You showed up just in time",id:"ZKK"},
  {lyric:"This love is good, this love is bad This love is alive, back from the dead (oh, oh, oh)" ,id:"ZXX"},{lyric:"These hands had to let it go free and This love came back to me (oh, oh, oh)",id:"ZKK"},
  {lyric:"This love left a permanent mark This love is glowing in the dark (oh, oh, oh)",id:"ZWWW"},{lyric:"These hands had to let it go free and This love came back to me (oh, oh, oh)",id:"ZLL"},
  {lyric:"This love This love This love This love This love",id:"ZMM"},
  {lyric:"Your kiss, my cheek, I watched you leave Your smile, my ghost,",id:"ZTT"}, {lyric:"I fell to my knees When you're young, you just run But you come back to what you need",id:"ZNN"},
  {lyric:"This love is good, this love is bad This love is alive, back from the dead (oh, oh, oh)", id:"ZSS"},{lyric:"These hands had to let it go free and This love came back to me (oh, oh, oh)",id:"ZOO"},
  {lyric:"This love left a permanent mark This love is glowing in the dark (oh, oh, oh)",id:"ZPP"},
  {lyric:"These hands had to let it go free and This love came back to me (oh, oh, oh)",id:"ZQQ"},
  {lyric:"This love, oh This love This love This love This love came back to me, oh, oh, oh",id:"ZRR"},
];
